name: Setup CI Environment
inputs:
  branch:
    type: string
  python-version:
    default: "3.9"
    type: string

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}
        submodules: recursive

    - name: Install CI Dependencies
      run: |
        pip install -r ci_requirements.txt
        echo "/home/runner/.local/bin" >> $GITHUB_PATH
