name: Run Tests
on:
  push:
    branches:
      - develop
    tags:  # ignores tag pushes
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        python-version:
          #- "3.8"
          - "3.9"
          #- "3.10"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions/setup_environment
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Install Project
        run: |
          pip3 install .

      - name: Run Tests
        run:
          pytest --no-header -v test
